/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Error = IDL.Variant({
  'FrontendOriginsNotConfigured' : IDL.Null,
  'MixedSsoSources' : IDL.Record({
    'otherKeys' : IDL.Vec(IDL.Text),
    'ssoKeys' : IDL.Vec(IDL.Text),
  }),
  'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
  'MalformedCandid' : IDL.Null,
  'AmbiguousAttribute' : IDL.Record({
    'field' : IDL.Text,
    'sources' : IDL.Vec(IDL.Text),
  }),
  'NoAttributes' : IDL.Null,
  'UnknownNonce' : IDL.Null,
  'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
  'MissingField' : IDL.Text,
  'FrontendOriginMismatch' : IDL.Record({
    'got' : IDL.Text,
    'expected' : IDL.Vec(IDL.Text),
  }),
});
export const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
export const Address = IDL.Record({
  'area' : IDL.Text,
  'fullName' : IDL.Text,
  'instructions' : IDL.Text,
  'landmark' : IDL.Text,
  'mobile' : IDL.Text,
  'pincode' : IDL.Text,
  'houseFlat' : IDL.Text,
});
export const AddressId = IDL.Nat;
export const ProductId = IDL.Nat;
export const Paise = IDL.Nat;
export const CartError = IDL.Variant({
  'productNotFound' : ProductId,
  'couponInactive' : IDL.Text,
  'invalidAddress' : IDL.Text,
  'couponNotFound' : IDL.Text,
  'outOfStock' : ProductId,
  'invalidPincode' : IDL.Text,
  'couponMinOrderNotMet' : IDL.Record({ 'actual' : Paise, 'required' : Paise }),
  'invalidMobile' : IDL.Text,
  'invalidQuantity' : IDL.Null,
  'emptyCart' : IDL.Null,
});
export const CategoryInput = IDL.Record({
  'name' : IDL.Text,
  'imageUrl' : IDL.Text,
});
export const CategoryId = IDL.Nat;
export const CouponInput = IDL.Record({
  'active' : IDL.Bool,
  'maxDiscount' : Paise,
  'code' : IDL.Text,
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'minOrderValue' : Paise,
});
export const CouponId = IDL.Nat;
export const PackSize = IDL.Text;
export const ProductInput = IDL.Record({
  'categoryId' : CategoryId,
  'stockQuantity' : IDL.Nat,
  'originalPrice' : Paise,
  'packSize' : PackSize,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'imageUrl' : IDL.Text,
  'discountPrice' : Paise,
  'brand' : IDL.Text,
});
export const Coupon = IDL.Record({
  'id' : CouponId,
  'active' : IDL.Bool,
  'maxDiscount' : Paise,
  'code' : IDL.Text,
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'minOrderValue' : Paise,
});
export const CustomerSummary = IDL.Record({
  'principal' : IDL.Principal,
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
  'orderCount' : IDL.Nat,
  'totalSpent' : Paise,
});
export const OrderId = IDL.Nat;
export const OrderStatus = IDL.Variant({
  'outForDelivery' : IDL.Null,
  'placed' : IDL.Null,
  'packing' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'cod' : IDL.Null,
  'online' : IDL.Null,
});
export const OrderLine = IDL.Record({
  'originalUnitPrice' : Paise,
  'packSize' : PackSize,
  'name' : IDL.Text,
  'lineTotal' : Paise,
  'productId' : ProductId,
  'imageUrl' : IDL.Text,
  'quantity' : IDL.Nat,
  'brand' : IDL.Text,
  'unitPrice' : Paise,
});
export const Timestamp = IDL.Int;
export const Order = IDL.Record({
  'id' : OrderId,
  'status' : OrderStatus,
  'couponCode' : IDL.Opt(IDL.Text),
  'deliveryCharge' : Paise,
  'total' : Paise,
  'paymentMethod' : PaymentMethod,
  'lines' : IDL.Vec(OrderLine),
  'couponDiscount' : Paise,
  'updatedAt' : Timestamp,
  'address' : Address,
  'placedAt' : Timestamp,
  'subtotal' : Paise,
  'discountTotal' : Paise,
});
export const SalesSummary = IDL.Record({
  'totalProducts' : IDL.Nat,
  'ordersByStatus' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
  'totalOrders' : IDL.Nat,
  'totalRevenue' : Paise,
  'totalCustomers' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Value = IDL.Variant({
  'int' : IDL.Int,
  'nat' : IDL.Nat,
  'float' : IDL.Float64,
  'bool' : IDL.Bool,
  'null' : IDL.Null,
  'text' : IDL.Text,
});
export const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
export const Result = IDL.Record({
  'hasMore' : IDL.Bool,
  'rows' : IDL.Vec(IDL.Vec(Cell)),
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const CartItemView = IDL.Record({
  'inStock' : IDL.Bool,
  'originalUnitPrice' : Paise,
  'packSize' : PackSize,
  'name' : IDL.Text,
  'lineTotal' : Paise,
  'productId' : ProductId,
  'imageUrl' : IDL.Text,
  'quantity' : IDL.Nat,
  'brand' : IDL.Text,
  'unitPrice' : Paise,
});
export const CartView = IDL.Record({
  'couponCode' : IDL.Opt(IDL.Text),
  'deliveryCharge' : Paise,
  'total' : Paise,
  'itemCount' : IDL.Nat,
  'couponDiscount' : Paise,
  'items' : IDL.Vec(CartItemView),
  'freeDeliveryThreshold' : Paise,
  'subtotal' : Paise,
  'discountTotal' : Paise,
});
export const Category = IDL.Record({
  'id' : CategoryId,
  'name' : IDL.Text,
  'productCount' : IDL.Nat,
  'imageUrl' : IDL.Text,
});
export const Product = IDL.Record({
  'id' : ProductId,
  'categoryId' : CategoryId,
  'stockQuantity' : IDL.Nat,
  'inStock' : IDL.Bool,
  'originalPrice' : Paise,
  'packSize' : PackSize,
  'name' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'imageUrl' : IDL.Text,
  'discountPrice' : Paise,
  'brand' : IDL.Text,
});
export const HomeFeed = IDL.Record({
  'bestSelling' : IDL.Vec(Product),
  'recommended' : IDL.Vec(Product),
  'discounted' : IDL.Vec(Product),
  'newArrivals' : IDL.Vec(Product),
  'todaysDeals' : IDL.Vec(Product),
});
export const SavedAddress = IDL.Record({
  'id' : AddressId,
  'address' : Address,
});
export const NotificationId = IDL.Nat;
export const Notification = IDL.Record({
  'id' : NotificationId,
  'title' : IDL.Text,
  'body' : IDL.Text,
  'createdAt' : Timestamp,
  'read' : IDL.Bool,
});
export const CheckoutInput = IDL.Record({
  'couponCode' : IDL.Opt(IDL.Text),
  'paymentMethod' : PaymentMethod,
  'address' : Address,
});
export const ProductFilter = IDL.Record({
  'categoryId' : IDL.Opt(CategoryId),
  'inStockOnly' : IDL.Bool,
  'maxPrice' : IDL.Opt(Paise),
  'searchTerm' : IDL.Opt(IDL.Text),
  'minPrice' : IDL.Opt(Paise),
});

export const idlService = IDL.Service({
  '_initialize_access_control' : IDL.Func([], [], []),
  '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
  '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
  'addAddress' : IDL.Func([Address], [AddressId], []),
  'addToCart' : IDL.Func([ProductId, IDL.Nat], [CartError], []),
  'adminAddCategory' : IDL.Func([CategoryInput], [CategoryId], []),
  'adminAddCoupon' : IDL.Func([CouponInput], [CouponId], []),
  'adminAddProduct' : IDL.Func([ProductInput], [ProductId], []),
  'adminDeleteCoupon' : IDL.Func([CouponId], [IDL.Bool], []),
  'adminDeleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'adminListCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'adminListCustomers' : IDL.Func([], [IDL.Vec(CustomerSummary)], ['query']),
  'adminListOrders' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Principal, Order))],
      ['query'],
    ),
  'adminSalesSummary' : IDL.Func([], [SalesSummary], ['query']),
  'adminSetOrderStatus' : IDL.Func(
      [IDL.Principal, OrderId, OrderStatus],
      [IDL.Bool],
      [],
    ),
  'adminSetStock' : IDL.Func([ProductId, IDL.Nat], [IDL.Bool], []),
  'adminUpdateCoupon' : IDL.Func([CouponId, CouponInput], [IDL.Bool], []),
  'adminUpdateProduct' : IDL.Func([ProductId, ProductInput], [IDL.Bool], []),
  'applyCoupon' : IDL.Func([IDL.Text], [CartError], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'clearCart' : IDL.Func([], [], []),
  'deleteAddress' : IDL.Func([AddressId], [IDL.Bool], []),
  'execute' : IDL.Func([IDL.Text], [Result], ['query']),
  'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
  'getCallerEmail' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCart' : IDL.Func([], [CartView], ['query']),
  'getCategory' : IDL.Func([CategoryId], [IDL.Opt(Category)], ['query']),
  'getHomeFeeds' : IDL.Func([], [HomeFeed], ['query']),
  'getMyOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
  'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listActiveCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'listAddresses' : IDL.Func([], [IDL.Vec(SavedAddress)], ['query']),
  'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'listNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'listProductsByCategory' : IDL.Func(
      [CategoryId],
      [IDL.Vec(Product)],
      ['query'],
    ),
  'listRecentlyViewed' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
  'listWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
  'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
  'placeOrder' : IDL.Func([CheckoutInput], [OrderId], []),
  'recordRecentlyViewed' : IDL.Func([ProductId], [], []),
  'removeCoupon' : IDL.Func([], [], []),
  'removeFromCart' : IDL.Func([ProductId], [IDL.Bool], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'schema' : IDL.Func([], [IDL.Text], ['query']),
  'searchProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
  'setCartQuantity' : IDL.Func([ProductId, IDL.Nat], [CartError], []),
  'toggleWishlist' : IDL.Func([ProductId], [IDL.Bool], []),
  'updateAddress' : IDL.Func([AddressId, Address], [IDL.Bool], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Error = IDL.Variant({
    'FrontendOriginsNotConfigured' : IDL.Null,
    'MixedSsoSources' : IDL.Record({
      'otherKeys' : IDL.Vec(IDL.Text),
      'ssoKeys' : IDL.Vec(IDL.Text),
    }),
    'Stale' : IDL.Record({ 'ageNs' : IDL.Nat }),
    'MalformedCandid' : IDL.Null,
    'AmbiguousAttribute' : IDL.Record({
      'field' : IDL.Text,
      'sources' : IDL.Vec(IDL.Text),
    }),
    'NoAttributes' : IDL.Null,
    'UnknownNonce' : IDL.Null,
    'UntrustedSsoSource' : IDL.Record({ 'domain' : IDL.Text }),
    'MissingField' : IDL.Text,
    'FrontendOriginMismatch' : IDL.Record({
      'got' : IDL.Text,
      'expected' : IDL.Vec(IDL.Text),
    }),
  });
  const Result__1 = IDL.Variant({ 'ok' : IDL.Null, 'err' : Error });
  const Address = IDL.Record({
    'area' : IDL.Text,
    'fullName' : IDL.Text,
    'instructions' : IDL.Text,
    'landmark' : IDL.Text,
    'mobile' : IDL.Text,
    'pincode' : IDL.Text,
    'houseFlat' : IDL.Text,
  });
  const AddressId = IDL.Nat;
  const ProductId = IDL.Nat;
  const Paise = IDL.Nat;
  const CartError = IDL.Variant({
    'productNotFound' : ProductId,
    'couponInactive' : IDL.Text,
    'invalidAddress' : IDL.Text,
    'couponNotFound' : IDL.Text,
    'outOfStock' : ProductId,
    'invalidPincode' : IDL.Text,
    'couponMinOrderNotMet' : IDL.Record({
      'actual' : Paise,
      'required' : Paise,
    }),
    'invalidMobile' : IDL.Text,
    'invalidQuantity' : IDL.Null,
    'emptyCart' : IDL.Null,
  });
  const CategoryInput = IDL.Record({
    'name' : IDL.Text,
    'imageUrl' : IDL.Text,
  });
  const CategoryId = IDL.Nat;
  const CouponInput = IDL.Record({
    'active' : IDL.Bool,
    'maxDiscount' : Paise,
    'code' : IDL.Text,
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'minOrderValue' : Paise,
  });
  const CouponId = IDL.Nat;
  const PackSize = IDL.Text;
  const ProductInput = IDL.Record({
    'categoryId' : CategoryId,
    'stockQuantity' : IDL.Nat,
    'originalPrice' : Paise,
    'packSize' : PackSize,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'imageUrl' : IDL.Text,
    'discountPrice' : Paise,
    'brand' : IDL.Text,
  });
  const Coupon = IDL.Record({
    'id' : CouponId,
    'active' : IDL.Bool,
    'maxDiscount' : Paise,
    'code' : IDL.Text,
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'minOrderValue' : Paise,
  });
  const CustomerSummary = IDL.Record({
    'principal' : IDL.Principal,
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
    'orderCount' : IDL.Nat,
    'totalSpent' : Paise,
  });
  const OrderId = IDL.Nat;
  const OrderStatus = IDL.Variant({
    'outForDelivery' : IDL.Null,
    'placed' : IDL.Null,
    'packing' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({ 'cod' : IDL.Null, 'online' : IDL.Null });
  const OrderLine = IDL.Record({
    'originalUnitPrice' : Paise,
    'packSize' : PackSize,
    'name' : IDL.Text,
    'lineTotal' : Paise,
    'productId' : ProductId,
    'imageUrl' : IDL.Text,
    'quantity' : IDL.Nat,
    'brand' : IDL.Text,
    'unitPrice' : Paise,
  });
  const Timestamp = IDL.Int;
  const Order = IDL.Record({
    'id' : OrderId,
    'status' : OrderStatus,
    'couponCode' : IDL.Opt(IDL.Text),
    'deliveryCharge' : Paise,
    'total' : Paise,
    'paymentMethod' : PaymentMethod,
    'lines' : IDL.Vec(OrderLine),
    'couponDiscount' : Paise,
    'updatedAt' : Timestamp,
    'address' : Address,
    'placedAt' : Timestamp,
    'subtotal' : Paise,
    'discountTotal' : Paise,
  });
  const SalesSummary = IDL.Record({
    'totalProducts' : IDL.Nat,
    'ordersByStatus' : IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat)),
    'totalOrders' : IDL.Nat,
    'totalRevenue' : Paise,
    'totalCustomers' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Value = IDL.Variant({
    'int' : IDL.Int,
    'nat' : IDL.Nat,
    'float' : IDL.Float64,
    'bool' : IDL.Bool,
    'null' : IDL.Null,
    'text' : IDL.Text,
  });
  const Cell = IDL.Record({ 'value' : Value, 'name' : IDL.Text });
  const Result = IDL.Record({
    'hasMore' : IDL.Bool,
    'rows' : IDL.Vec(IDL.Vec(Cell)),
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const CartItemView = IDL.Record({
    'inStock' : IDL.Bool,
    'originalUnitPrice' : Paise,
    'packSize' : PackSize,
    'name' : IDL.Text,
    'lineTotal' : Paise,
    'productId' : ProductId,
    'imageUrl' : IDL.Text,
    'quantity' : IDL.Nat,
    'brand' : IDL.Text,
    'unitPrice' : Paise,
  });
  const CartView = IDL.Record({
    'couponCode' : IDL.Opt(IDL.Text),
    'deliveryCharge' : Paise,
    'total' : Paise,
    'itemCount' : IDL.Nat,
    'couponDiscount' : Paise,
    'items' : IDL.Vec(CartItemView),
    'freeDeliveryThreshold' : Paise,
    'subtotal' : Paise,
    'discountTotal' : Paise,
  });
  const Category = IDL.Record({
    'id' : CategoryId,
    'name' : IDL.Text,
    'productCount' : IDL.Nat,
    'imageUrl' : IDL.Text,
  });
  const Product = IDL.Record({
    'id' : ProductId,
    'categoryId' : CategoryId,
    'stockQuantity' : IDL.Nat,
    'inStock' : IDL.Bool,
    'originalPrice' : Paise,
    'packSize' : PackSize,
    'name' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'imageUrl' : IDL.Text,
    'discountPrice' : Paise,
    'brand' : IDL.Text,
  });
  const HomeFeed = IDL.Record({
    'bestSelling' : IDL.Vec(Product),
    'recommended' : IDL.Vec(Product),
    'discounted' : IDL.Vec(Product),
    'newArrivals' : IDL.Vec(Product),
    'todaysDeals' : IDL.Vec(Product),
  });
  const SavedAddress = IDL.Record({ 'id' : AddressId, 'address' : Address });
  const NotificationId = IDL.Nat;
  const Notification = IDL.Record({
    'id' : NotificationId,
    'title' : IDL.Text,
    'body' : IDL.Text,
    'createdAt' : Timestamp,
    'read' : IDL.Bool,
  });
  const CheckoutInput = IDL.Record({
    'couponCode' : IDL.Opt(IDL.Text),
    'paymentMethod' : PaymentMethod,
    'address' : Address,
  });
  const ProductFilter = IDL.Record({
    'categoryId' : IDL.Opt(CategoryId),
    'inStockOnly' : IDL.Bool,
    'maxPrice' : IDL.Opt(Paise),
    'searchTerm' : IDL.Opt(IDL.Text),
    'minPrice' : IDL.Opt(Paise),
  });
  
  return IDL.Service({
    '_initialize_access_control' : IDL.Func([], [], []),
    '_internet_identity_sign_in_finish' : IDL.Func([], [Result__1], []),
    '_internet_identity_sign_in_start' : IDL.Func([], [IDL.Vec(IDL.Nat8)], []),
    'addAddress' : IDL.Func([Address], [AddressId], []),
    'addToCart' : IDL.Func([ProductId, IDL.Nat], [CartError], []),
    'adminAddCategory' : IDL.Func([CategoryInput], [CategoryId], []),
    'adminAddCoupon' : IDL.Func([CouponInput], [CouponId], []),
    'adminAddProduct' : IDL.Func([ProductInput], [ProductId], []),
    'adminDeleteCoupon' : IDL.Func([CouponId], [IDL.Bool], []),
    'adminDeleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'adminListCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'adminListCustomers' : IDL.Func([], [IDL.Vec(CustomerSummary)], ['query']),
    'adminListOrders' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Principal, Order))],
        ['query'],
      ),
    'adminSalesSummary' : IDL.Func([], [SalesSummary], ['query']),
    'adminSetOrderStatus' : IDL.Func(
        [IDL.Principal, OrderId, OrderStatus],
        [IDL.Bool],
        [],
      ),
    'adminSetStock' : IDL.Func([ProductId, IDL.Nat], [IDL.Bool], []),
    'adminUpdateCoupon' : IDL.Func([CouponId, CouponInput], [IDL.Bool], []),
    'adminUpdateProduct' : IDL.Func([ProductId, ProductInput], [IDL.Bool], []),
    'applyCoupon' : IDL.Func([IDL.Text], [CartError], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'clearCart' : IDL.Func([], [], []),
    'deleteAddress' : IDL.Func([AddressId], [IDL.Bool], []),
    'execute' : IDL.Func([IDL.Text], [Result], ['query']),
    'getApiDoc' : IDL.Func([], [IDL.Text], ['query']),
    'getCallerEmail' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCart' : IDL.Func([], [CartView], ['query']),
    'getCategory' : IDL.Func([CategoryId], [IDL.Opt(Category)], ['query']),
    'getHomeFeeds' : IDL.Func([], [HomeFeed], ['query']),
    'getMyOrder' : IDL.Func([OrderId], [IDL.Opt(Order)], ['query']),
    'getProduct' : IDL.Func([ProductId], [IDL.Opt(Product)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listActiveCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'listAddresses' : IDL.Func([], [IDL.Vec(SavedAddress)], ['query']),
    'listCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'listMyOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'listNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'listProductsByCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'listRecentlyViewed' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
    'listWishlist' : IDL.Func([], [IDL.Vec(ProductId)], ['query']),
    'markNotificationRead' : IDL.Func([NotificationId], [IDL.Bool], []),
    'placeOrder' : IDL.Func([CheckoutInput], [OrderId], []),
    'recordRecentlyViewed' : IDL.Func([ProductId], [], []),
    'removeCoupon' : IDL.Func([], [], []),
    'removeFromCart' : IDL.Func([ProductId], [IDL.Bool], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'schema' : IDL.Func([], [IDL.Text], ['query']),
    'searchProducts' : IDL.Func([ProductFilter], [IDL.Vec(Product)], ['query']),
    'setCartQuantity' : IDL.Func([ProductId, IDL.Nat], [CartError], []),
    'toggleWishlist' : IDL.Func([ProductId], [IDL.Bool], []),
    'updateAddress' : IDL.Func([AddressId, Address], [IDL.Bool], []),
  });
};

export const init = ({ IDL }) => { return []; };