/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'area' : string,
  'fullName' : string,
  'instructions' : string,
  'landmark' : string,
  'mobile' : string,
  'pincode' : string,
  'houseFlat' : string,
}
export type AddressId = bigint;
export type CartError = { 'productNotFound' : ProductId } |
  { 'couponInactive' : string } |
  { 'invalidAddress' : string } |
  { 'couponNotFound' : string } |
  { 'outOfStock' : ProductId } |
  { 'invalidPincode' : string } |
  { 'couponMinOrderNotMet' : { 'actual' : Paise, 'required' : Paise } } |
  { 'invalidMobile' : string } |
  { 'invalidQuantity' : null } |
  { 'emptyCart' : null };
export interface CartItemView {
  'inStock' : boolean,
  'originalUnitPrice' : Paise,
  'packSize' : PackSize,
  'name' : string,
  'lineTotal' : Paise,
  'productId' : ProductId,
  'imageUrl' : string,
  'quantity' : bigint,
  'brand' : string,
  'unitPrice' : Paise,
}
export interface CartView {
  'couponCode' : [] | [string],
  'deliveryCharge' : Paise,
  'total' : Paise,
  'itemCount' : bigint,
  'couponDiscount' : Paise,
  'items' : Array<CartItemView>,
  'freeDeliveryThreshold' : Paise,
  'subtotal' : Paise,
  'discountTotal' : Paise,
}
export interface Category {
  'id' : CategoryId,
  'name' : string,
  'productCount' : bigint,
  'imageUrl' : string,
}
export type CategoryId = bigint;
export interface CategoryInput { 'name' : string, 'imageUrl' : string }
export interface Cell { 'value' : Value, 'name' : string }
export interface CheckoutInput {
  'couponCode' : [] | [string],
  'paymentMethod' : PaymentMethod,
  'address' : Address,
}
export interface Coupon {
  'id' : CouponId,
  'active' : boolean,
  'maxDiscount' : Paise,
  'code' : string,
  'description' : string,
  'discountPercent' : bigint,
  'minOrderValue' : Paise,
}
export type CouponId = bigint;
export interface CouponInput {
  'active' : boolean,
  'maxDiscount' : Paise,
  'code' : string,
  'description' : string,
  'discountPercent' : bigint,
  'minOrderValue' : Paise,
}
export interface CustomerSummary {
  'principal' : Principal,
  'name' : string,
  'email' : [] | [string],
  'orderCount' : bigint,
  'totalSpent' : Paise,
}
export type Error = { 'FrontendOriginsNotConfigured' : null } |
  {
    'MixedSsoSources' : {
      'otherKeys' : Array<string>,
      'ssoKeys' : Array<string>,
    }
  } |
  { 'Stale' : { 'ageNs' : bigint } } |
  { 'MalformedCandid' : null } |
  { 'AmbiguousAttribute' : { 'field' : string, 'sources' : Array<string> } } |
  { 'NoAttributes' : null } |
  { 'UnknownNonce' : null } |
  { 'UntrustedSsoSource' : { 'domain' : string } } |
  { 'MissingField' : string } |
  { 'FrontendOriginMismatch' : { 'got' : string, 'expected' : Array<string> } };
export interface HomeFeed {
  'bestSelling' : Array<Product>,
  'recommended' : Array<Product>,
  'discounted' : Array<Product>,
  'newArrivals' : Array<Product>,
  'todaysDeals' : Array<Product>,
}
export interface Notification {
  'id' : NotificationId,
  'title' : string,
  'body' : string,
  'createdAt' : Timestamp,
  'read' : boolean,
}
export type NotificationId = bigint;
export interface Order {
  'id' : OrderId,
  'status' : OrderStatus,
  'couponCode' : [] | [string],
  'deliveryCharge' : Paise,
  'total' : Paise,
  'paymentMethod' : PaymentMethod,
  'lines' : Array<OrderLine>,
  'couponDiscount' : Paise,
  'updatedAt' : Timestamp,
  'address' : Address,
  'placedAt' : Timestamp,
  'subtotal' : Paise,
  'discountTotal' : Paise,
}
export type OrderId = bigint;
export interface OrderLine {
  'originalUnitPrice' : Paise,
  'packSize' : PackSize,
  'name' : string,
  'lineTotal' : Paise,
  'productId' : ProductId,
  'imageUrl' : string,
  'quantity' : bigint,
  'brand' : string,
  'unitPrice' : Paise,
}
export type OrderStatus = { 'outForDelivery' : null } |
  { 'placed' : null } |
  { 'packing' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export type PackSize = string;
export type Paise = bigint;
export type PaymentMethod = { 'cod' : null } |
  { 'online' : null };
export interface Product {
  'id' : ProductId,
  'categoryId' : CategoryId,
  'stockQuantity' : bigint,
  'inStock' : boolean,
  'originalPrice' : Paise,
  'packSize' : PackSize,
  'name' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'discountPercent' : bigint,
  'imageUrl' : string,
  'discountPrice' : Paise,
  'brand' : string,
}
export interface ProductFilter {
  'categoryId' : [] | [CategoryId],
  'inStockOnly' : boolean,
  'maxPrice' : [] | [Paise],
  'searchTerm' : [] | [string],
  'minPrice' : [] | [Paise],
}
export type ProductId = bigint;
export interface ProductInput {
  'categoryId' : CategoryId,
  'stockQuantity' : bigint,
  'originalPrice' : Paise,
  'packSize' : PackSize,
  'name' : string,
  'description' : string,
  'imageUrl' : string,
  'discountPrice' : Paise,
  'brand' : string,
}
export interface Result { 'hasMore' : boolean, 'rows' : Array<Array<Cell>> }
export type Result__1 = { 'ok' : null } |
  { 'err' : Error };
export interface SalesSummary {
  'totalProducts' : bigint,
  'ordersByStatus' : Array<[string, bigint]>,
  'totalOrders' : bigint,
  'totalRevenue' : Paise,
  'totalCustomers' : bigint,
}
export interface SavedAddress { 'id' : AddressId, 'address' : Address }
export type Timestamp = bigint;
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type Value = { 'int' : bigint } |
  { 'nat' : bigint } |
  { 'float' : number } |
  { 'bool' : boolean } |
  { 'null' : null } |
  { 'text' : string };
export interface _SERVICE {
  '_initialize_access_control' : ActorMethod<[], undefined>,
  '_internet_identity_sign_in_finish' : ActorMethod<[], Result__1>,
  '_internet_identity_sign_in_start' : ActorMethod<[], Uint8Array>,
  /**
   * / Add a saved address.
   */
  'addAddress' : ActorMethod<[Address], AddressId>,
  /**
   * / Add a product to the caller's cart.
   */
  'addToCart' : ActorMethod<[ProductId, bigint], CartError>,
  /**
   * / Add a category (admin only).
   */
  'adminAddCategory' : ActorMethod<[CategoryInput], CategoryId>,
  /**
   * / Add a coupon (admin only).
   */
  'adminAddCoupon' : ActorMethod<[CouponInput], CouponId>,
  /**
   * / Add a product (admin only).
   */
  'adminAddProduct' : ActorMethod<[ProductInput], ProductId>,
  /**
   * / Delete a coupon (admin only).
   */
  'adminDeleteCoupon' : ActorMethod<[CouponId], boolean>,
  /**
   * / Delete a product (admin only).
   */
  'adminDeleteProduct' : ActorMethod<[ProductId], boolean>,
  /**
   * / List all coupons (admin only).
   */
  'adminListCoupons' : ActorMethod<[], Array<Coupon>>,
  /**
   * / List customer summaries (admin only).
   */
  'adminListCustomers' : ActorMethod<[], Array<CustomerSummary>>,
  /**
   * / List all orders across customers (admin only).
   */
  'adminListOrders' : ActorMethod<[], Array<[Principal, Order]>>,
  /**
   * / Aggregate sales figures (admin only).
   */
  'adminSalesSummary' : ActorMethod<[], SalesSummary>,
  /**
   * / Change an order's status (admin only).
   */
  'adminSetOrderStatus' : ActorMethod<
    [Principal, OrderId, OrderStatus],
    boolean
  >,
  /**
   * / Set a product's stock quantity (admin only).
   */
  'adminSetStock' : ActorMethod<[ProductId, bigint], boolean>,
  /**
   * / Update a coupon (admin only).
   */
  'adminUpdateCoupon' : ActorMethod<[CouponId, CouponInput], boolean>,
  /**
   * / Update a product (admin only).
   */
  'adminUpdateProduct' : ActorMethod<[ProductId, ProductInput], boolean>,
  /**
   * / Apply a coupon code to the caller's cart.
   */
  'applyCoupon' : ActorMethod<[string], CartError>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  /**
   * / Clear the caller's cart.
   */
  'clearCart' : ActorMethod<[], undefined>,
  /**
   * / Delete a saved address.
   */
  'deleteAddress' : ActorMethod<[AddressId], boolean>,
  'execute' : ActorMethod<[string], Result>,
  /**
   * / Return the backend's behavioral API documentation as Markdown.
   */
  'getApiDoc' : ActorMethod<[], string>,
  /**
   * / Get the caller's verified email, when available.
   */
  'getCallerEmail' : ActorMethod<[], [] | [string]>,
  /**
   * / Get the caller's profile.
   */
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  /**
   * / Get the caller's cart with totals and applied coupon.
   */
  'getCart' : ActorMethod<[], CartView>,
  /**
   * / Fetch one category.
   */
  'getCategory' : ActorMethod<[CategoryId], [] | [Category]>,
  /**
   * / Home screen feeds: deals, best selling, new arrivals, discounted, recommended.
   */
  'getHomeFeeds' : ActorMethod<[], HomeFeed>,
  /**
   * / Fetch one of the caller's orders.
   */
  'getMyOrder' : ActorMethod<[OrderId], [] | [Order]>,
  /**
   * / Fetch one product's detail.
   */
  'getProduct' : ActorMethod<[ProductId], [] | [Product]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  /**
   * / List the active coupons available to shoppers (public, no admin role required).
   */
  'listActiveCoupons' : ActorMethod<[], Array<Coupon>>,
  /**
   * / List the caller's saved addresses.
   */
  'listAddresses' : ActorMethod<[], Array<SavedAddress>>,
  /**
   * / List all grocery categories with product counts.
   */
  'listCategories' : ActorMethod<[], Array<Category>>,
  /**
   * / List the caller's orders, newest first.
   */
  'listMyOrders' : ActorMethod<[], Array<Order>>,
  /**
   * / List the caller's notifications, newest first.
   */
  'listNotifications' : ActorMethod<[], Array<Notification>>,
  /**
   * / List products in a category.
   */
  'listProductsByCategory' : ActorMethod<[CategoryId], Array<Product>>,
  /**
   * / List the caller's recently viewed product ids, newest first.
   */
  'listRecentlyViewed' : ActorMethod<[], Array<ProductId>>,
  /**
   * / List the caller's wishlist product ids.
   */
  'listWishlist' : ActorMethod<[], Array<ProductId>>,
  /**
   * / Mark a notification as read.
   */
  'markNotificationRead' : ActorMethod<[NotificationId], boolean>,
  /**
   * / Place an order from the caller's cart.
   */
  'placeOrder' : ActorMethod<[CheckoutInput], OrderId>,
  /**
   * / Record a product as recently viewed by the caller.
   */
  'recordRecentlyViewed' : ActorMethod<[ProductId], undefined>,
  /**
   * / Remove the applied coupon from the caller's cart.
   */
  'removeCoupon' : ActorMethod<[], undefined>,
  /**
   * / Remove a product from the caller's cart.
   */
  'removeFromCart' : ActorMethod<[ProductId], boolean>,
  /**
   * / Save the caller's profile.
   */
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'schema' : ActorMethod<[], string>,
  /**
   * / Search and filter products by name, brand, category and price range.
   */
  'searchProducts' : ActorMethod<[ProductFilter], Array<Product>>,
  /**
   * / Set a cart line's quantity (0 removes it).
   */
  'setCartQuantity' : ActorMethod<[ProductId, bigint], CartError>,
  /**
   * / Toggle a product in the caller's wishlist. Returns true when now present.
   */
  'toggleWishlist' : ActorMethod<[ProductId], boolean>,
  /**
   * / Update a saved address.
   */
  'updateAddress' : ActorMethod<[AddressId, Address], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];