/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeineai/bindgen@0.3.1.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
import { ExternalBlob } from "@caffeineai/object-storage";
export { ExternalBlob } from "@caffeineai/object-storage";
export interface Address {
    area: string;
    fullName: string;
    instructions: string;
    landmark: string;
    mobile: string;
    pincode: string;
    houseFlat: string;
}
export type AddressId = bigint;
export type CartError = {
    __kind__: "productNotFound";
    productNotFound: ProductId;
} | {
    __kind__: "couponInactive";
    couponInactive: string;
} | {
    __kind__: "invalidAddress";
    invalidAddress: string;
} | {
    __kind__: "couponNotFound";
    couponNotFound: string;
} | {
    __kind__: "outOfStock";
    outOfStock: ProductId;
} | {
    __kind__: "invalidPincode";
    invalidPincode: string;
} | {
    __kind__: "couponMinOrderNotMet";
    couponMinOrderNotMet: {
        actual: Paise;
        required: Paise;
    };
} | {
    __kind__: "invalidMobile";
    invalidMobile: string;
} | {
    __kind__: "invalidQuantity";
    invalidQuantity: null;
} | {
    __kind__: "emptyCart";
    emptyCart: null;
};
export interface CartItemView {
    inStock: boolean;
    originalUnitPrice: Paise;
    packSize: PackSize;
    name: string;
    lineTotal: Paise;
    productId: ProductId;
    imageUrl: string;
    quantity: bigint;
    brand: string;
    unitPrice: Paise;
}
export interface CartView {
    couponCode?: string;
    deliveryCharge: Paise;
    total: Paise;
    itemCount: bigint;
    couponDiscount: Paise;
    items: Array<CartItemView>;
    freeDeliveryThreshold: Paise;
    subtotal: Paise;
    discountTotal: Paise;
}
export interface Category {
    id: CategoryId;
    name: string;
    productCount: bigint;
    imageUrl: string;
}
export type CategoryId = bigint;
export interface CategoryInput {
    name: string;
    imageUrl: string;
}
export interface Cell {
    value: Value;
    name: string;
}
export interface CheckoutInput {
    couponCode?: string;
    paymentMethod: PaymentMethod;
    address: Address;
}
export interface Coupon {
    id: CouponId;
    active: boolean;
    maxDiscount: Paise;
    code: string;
    description: string;
    discountPercent: bigint;
    minOrderValue: Paise;
}
export type CouponId = bigint;
export interface CouponInput {
    active: boolean;
    maxDiscount: Paise;
    code: string;
    description: string;
    discountPercent: bigint;
    minOrderValue: Paise;
}
export interface CustomerSummary {
    principal: Principal;
    name: string;
    email?: string;
    orderCount: bigint;
    totalSpent: Paise;
}
export type Error_ = {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
};
export interface HomeFeed {
    bestSelling: Array<Product>;
    recommended: Array<Product>;
    discounted: Array<Product>;
    newArrivals: Array<Product>;
    todaysDeals: Array<Product>;
}
export interface Notification {
    id: NotificationId;
    title: string;
    body: string;
    createdAt: Timestamp;
    read: boolean;
}
export type NotificationId = bigint;
export interface Order {
    id: OrderId;
    status: OrderStatus;
    couponCode?: string;
    deliveryCharge: Paise;
    total: Paise;
    paymentMethod: PaymentMethod;
    lines: Array<OrderLine>;
    couponDiscount: Paise;
    updatedAt: Timestamp;
    address: Address;
    placedAt: Timestamp;
    subtotal: Paise;
    discountTotal: Paise;
}
export type OrderId = bigint;
export interface OrderLine {
    originalUnitPrice: Paise;
    packSize: PackSize;
    name: string;
    lineTotal: Paise;
    productId: ProductId;
    imageUrl: string;
    quantity: bigint;
    brand: string;
    unitPrice: Paise;
}
export type PackSize = string;
export type Paise = bigint;
export interface Product {
    id: ProductId;
    categoryId: CategoryId;
    stockQuantity: bigint;
    inStock: boolean;
    originalPrice: Paise;
    packSize: PackSize;
    name: string;
    createdAt: Timestamp;
    description: string;
    discountPercent: bigint;
    imageUrl: string;
    discountPrice: Paise;
    brand: string;
}
export interface ProductFilter {
    categoryId?: CategoryId;
    inStockOnly: boolean;
    maxPrice?: Paise;
    searchTerm?: string;
    minPrice?: Paise;
}
export type ProductId = bigint;
export interface ProductInput {
    categoryId: CategoryId;
    stockQuantity: bigint;
    originalPrice: Paise;
    packSize: PackSize;
    name: string;
    description: string;
    imageUrl: string;
    discountPrice: Paise;
    brand: string;
}
export interface Result {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
}
export type Result__1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
};
export interface SalesSummary {
    totalProducts: bigint;
    ordersByStatus: Array<[string, bigint]>;
    totalOrders: bigint;
    totalRevenue: Paise;
    totalCustomers: bigint;
}
export interface SavedAddress {
    id: AddressId;
    address: Address;
}
export type Timestamp = bigint;
export interface UserProfile {
    name: string;
    email?: string;
}
export type Value = {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
};
export enum OrderStatus {
    outForDelivery = "outForDelivery",
    placed = "placed",
    packing = "packing",
    delivered = "delivered",
    confirmed = "confirmed"
}
export enum PaymentMethod {
    cod = "cod",
    online = "online"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initialize_access_control(): Promise<void>;
    _internet_identity_sign_in_finish(): Promise<Result__1>;
    _internet_identity_sign_in_start(): Promise<Uint8Array>;
    /**
     * / Add a saved address.
     */
    addAddress(address: Address): Promise<AddressId>;
    /**
     * / Add a product to the caller's cart.
     */
    addToCart(productId: ProductId, quantity: bigint): Promise<CartError>;
    /**
     * / Add a category (admin only).
     */
    adminAddCategory(input: CategoryInput): Promise<CategoryId>;
    /**
     * / Add a coupon (admin only).
     */
    adminAddCoupon(input: CouponInput): Promise<CouponId>;
    /**
     * / Add a product (admin only).
     */
    adminAddProduct(input: ProductInput): Promise<ProductId>;
    /**
     * / Delete a coupon (admin only).
     */
    adminDeleteCoupon(couponId: CouponId): Promise<boolean>;
    /**
     * / Delete a product (admin only).
     */
    adminDeleteProduct(productId: ProductId): Promise<boolean>;
    /**
     * / List all coupons (admin only).
     */
    adminListCoupons(): Promise<Array<Coupon>>;
    /**
     * / List customer summaries (admin only).
     */
    adminListCustomers(): Promise<Array<CustomerSummary>>;
    /**
     * / List all orders across customers (admin only).
     */
    adminListOrders(): Promise<Array<[Principal, Order]>>;
    /**
     * / Aggregate sales figures (admin only).
     */
    adminSalesSummary(): Promise<SalesSummary>;
    /**
     * / Change an order's status (admin only).
     */
    adminSetOrderStatus(customer: Principal, orderId: OrderId, status: OrderStatus): Promise<boolean>;
    /**
     * / Set a product's stock quantity (admin only).
     */
    adminSetStock(productId: ProductId, stockQuantity: bigint): Promise<boolean>;
    /**
     * / Update a coupon (admin only).
     */
    adminUpdateCoupon(couponId: CouponId, input: CouponInput): Promise<boolean>;
    /**
     * / Update a product (admin only).
     */
    adminUpdateProduct(productId: ProductId, input: ProductInput): Promise<boolean>;
    /**
     * / Apply a coupon code to the caller's cart.
     */
    applyCoupon(code: string): Promise<CartError>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    /**
     * / Clear the caller's cart.
     */
    clearCart(): Promise<void>;
    /**
     * / Delete a saved address.
     */
    deleteAddress(addressId: AddressId): Promise<boolean>;
    execute(qJson: string): Promise<Result>;
    /**
     * / Return the backend's behavioral API documentation as Markdown.
     */
    getApiDoc(): Promise<string>;
    /**
     * / Get the caller's verified email, when available.
     */
    getCallerEmail(): Promise<string | null>;
    /**
     * / Get the caller's profile.
     */
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    /**
     * / Get the caller's cart with totals and applied coupon.
     */
    getCart(): Promise<CartView>;
    /**
     * / Fetch one category.
     */
    getCategory(categoryId: CategoryId): Promise<Category | null>;
    /**
     * / Home screen feeds: deals, best selling, new arrivals, discounted, recommended.
     */
    getHomeFeeds(): Promise<HomeFeed>;
    /**
     * / Fetch one of the caller's orders.
     */
    getMyOrder(orderId: OrderId): Promise<Order | null>;
    /**
     * / Fetch one product's detail.
     */
    getProduct(productId: ProductId): Promise<Product | null>;
    isCallerAdmin(): Promise<boolean>;
    /**
     * / List the active coupons available to shoppers (public, no admin role required).
     */
    listActiveCoupons(): Promise<Array<Coupon>>;
    /**
     * / List the caller's saved addresses.
     */
    listAddresses(): Promise<Array<SavedAddress>>;
    /**
     * / List all grocery categories with product counts.
     */
    listCategories(): Promise<Array<Category>>;
    /**
     * / List the caller's orders, newest first.
     */
    listMyOrders(): Promise<Array<Order>>;
    /**
     * / List the caller's notifications, newest first.
     */
    listNotifications(): Promise<Array<Notification>>;
    /**
     * / List products in a category.
     */
    listProductsByCategory(categoryId: CategoryId): Promise<Array<Product>>;
    /**
     * / List the caller's recently viewed product ids, newest first.
     */
    listRecentlyViewed(): Promise<Array<ProductId>>;
    /**
     * / List the caller's wishlist product ids.
     */
    listWishlist(): Promise<Array<ProductId>>;
    /**
     * / Mark a notification as read.
     */
    markNotificationRead(notificationId: NotificationId): Promise<boolean>;
    /**
     * / Place an order from the caller's cart.
     */
    placeOrder(input: CheckoutInput): Promise<OrderId>;
    /**
     * / Record a product as recently viewed by the caller.
     */
    recordRecentlyViewed(productId: ProductId): Promise<void>;
    /**
     * / Remove the applied coupon from the caller's cart.
     */
    removeCoupon(): Promise<void>;
    /**
     * / Remove a product from the caller's cart.
     */
    removeFromCart(productId: ProductId): Promise<boolean>;
    /**
     * / Save the caller's profile.
     */
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    schema(): Promise<string>;
    /**
     * / Search and filter products by name, brand, category and price range.
     */
    searchProducts(filter: ProductFilter): Promise<Array<Product>>;
    /**
     * / Set a cart line's quantity (0 removes it).
     */
    setCartQuantity(productId: ProductId, quantity: bigint): Promise<CartError>;
    /**
     * / Toggle a product in the caller's wishlist. Returns true when now present.
     */
    toggleWishlist(productId: ProductId): Promise<boolean>;
    /**
     * / Update a saved address.
     */
    updateAddress(addressId: AddressId, address: Address): Promise<boolean>;
}
import type { Address as _Address, CartError as _CartError, CartItemView as _CartItemView, CartView as _CartView, Category as _Category, CategoryId as _CategoryId, Cell as _Cell, CheckoutInput as _CheckoutInput, CustomerSummary as _CustomerSummary, Error as _Error, Order as _Order, OrderId as _OrderId, OrderLine as _OrderLine, OrderStatus as _OrderStatus, Paise as _Paise, PaymentMethod as _PaymentMethod, Product as _Product, ProductFilter as _ProductFilter, ProductId as _ProductId, Result as _Result, Result__1 as _Result__1, Timestamp as _Timestamp, UserProfile as _UserProfile, UserRole as _UserRole, Value as _Value } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initialize_access_control(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initialize_access_control();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initialize_access_control();
            return result;
        }
    }
    async _internet_identity_sign_in_finish(): Promise<Result__1> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_finish();
                return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_finish();
            return from_candid_Result__1_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async _internet_identity_sign_in_start(): Promise<Uint8Array> {
        if (this.processError) {
            try {
                const result = await this.actor._internet_identity_sign_in_start();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._internet_identity_sign_in_start();
            return result;
        }
    }
    async addAddress(arg0: Address): Promise<AddressId> {
        if (this.processError) {
            try {
                const result = await this.actor.addAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAddress(arg0);
            return result;
        }
    }
    async addToCart(arg0: ProductId, arg1: bigint): Promise<CartError> {
        if (this.processError) {
            try {
                const result = await this.actor.addToCart(arg0, arg1);
                return from_candid_CartError_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addToCart(arg0, arg1);
            return from_candid_CartError_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminAddCategory(arg0: CategoryInput): Promise<CategoryId> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddCategory(arg0);
            return result;
        }
    }
    async adminAddCoupon(arg0: CouponInput): Promise<CouponId> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddCoupon(arg0);
            return result;
        }
    }
    async adminAddProduct(arg0: ProductInput): Promise<ProductId> {
        if (this.processError) {
            try {
                const result = await this.actor.adminAddProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminAddProduct(arg0);
            return result;
        }
    }
    async adminDeleteCoupon(arg0: CouponId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteCoupon(arg0);
            return result;
        }
    }
    async adminDeleteProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminDeleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminDeleteProduct(arg0);
            return result;
        }
    }
    async adminListCoupons(): Promise<Array<Coupon>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListCoupons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListCoupons();
            return result;
        }
    }
    async adminListCustomers(): Promise<Array<CustomerSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListCustomers();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListCustomers();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminListOrders(): Promise<Array<[Principal, Order]>> {
        if (this.processError) {
            try {
                const result = await this.actor.adminListOrders();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminListOrders();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminSalesSummary(): Promise<SalesSummary> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSalesSummary();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSalesSummary();
            return result;
        }
    }
    async adminSetOrderStatus(arg0: Principal, arg1: OrderId, arg2: OrderStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetOrderStatus(arg0, arg1, to_candid_OrderStatus_n17(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetOrderStatus(arg0, arg1, to_candid_OrderStatus_n17(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async adminSetStock(arg0: ProductId, arg1: bigint): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminSetStock(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminSetStock(arg0, arg1);
            return result;
        }
    }
    async adminUpdateCoupon(arg0: CouponId, arg1: CouponInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateCoupon(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateCoupon(arg0, arg1);
            return result;
        }
    }
    async adminUpdateProduct(arg0: ProductId, arg1: ProductInput): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUpdateProduct(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUpdateProduct(arg0, arg1);
            return result;
        }
    }
    async applyCoupon(arg0: string): Promise<CartError> {
        if (this.processError) {
            try {
                const result = await this.actor.applyCoupon(arg0);
                return from_candid_CartError_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.applyCoupon(arg0);
            return from_candid_CartError_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n18(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async clearCart(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.clearCart();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.clearCart();
            return result;
        }
    }
    async deleteAddress(arg0: AddressId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteAddress(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteAddress(arg0);
            return result;
        }
    }
    async execute(arg0: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.execute(arg0);
                return from_candid_Result_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.execute(arg0);
            return from_candid_Result_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getApiDoc(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.getApiDoc();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApiDoc();
            return result;
        }
    }
    async getCallerEmail(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerEmail();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerEmail();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCart(): Promise<CartView> {
        if (this.processError) {
            try {
                const result = await this.actor.getCart();
                return from_candid_CartView_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCart();
            return from_candid_CartView_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCategory(arg0: CategoryId): Promise<Category | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCategory(arg0);
                return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCategory(arg0);
            return from_candid_opt_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHomeFeeds(): Promise<HomeFeed> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomeFeeds();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomeFeeds();
            return result;
        }
    }
    async getMyOrder(arg0: OrderId): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyOrder(arg0);
                return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyOrder(arg0);
            return from_candid_opt_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProduct(arg0: ProductId): Promise<Product | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getProduct(arg0);
                return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProduct(arg0);
            return from_candid_opt_n35(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async listActiveCoupons(): Promise<Array<Coupon>> {
        if (this.processError) {
            try {
                const result = await this.actor.listActiveCoupons();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listActiveCoupons();
            return result;
        }
    }
    async listAddresses(): Promise<Array<SavedAddress>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAddresses();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAddresses();
            return result;
        }
    }
    async listCategories(): Promise<Array<Category>> {
        if (this.processError) {
            try {
                const result = await this.actor.listCategories();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listCategories();
            return result;
        }
    }
    async listMyOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.listMyOrders();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listMyOrders();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async listNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.listNotifications();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listNotifications();
            return result;
        }
    }
    async listProductsByCategory(arg0: CategoryId): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProductsByCategory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProductsByCategory(arg0);
            return result;
        }
    }
    async listRecentlyViewed(): Promise<Array<ProductId>> {
        if (this.processError) {
            try {
                const result = await this.actor.listRecentlyViewed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listRecentlyViewed();
            return result;
        }
    }
    async listWishlist(): Promise<Array<ProductId>> {
        if (this.processError) {
            try {
                const result = await this.actor.listWishlist();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listWishlist();
            return result;
        }
    }
    async markNotificationRead(arg0: NotificationId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async placeOrder(arg0: CheckoutInput): Promise<OrderId> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_CheckoutInput_n37(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_CheckoutInput_n37(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async recordRecentlyViewed(arg0: ProductId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.recordRecentlyViewed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.recordRecentlyViewed(arg0);
            return result;
        }
    }
    async removeCoupon(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeCoupon();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeCoupon();
            return result;
        }
    }
    async removeFromCart(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeFromCart(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeFromCart(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n40(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n40(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async schema(): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.schema();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.schema();
            return result;
        }
    }
    async searchProducts(arg0: ProductFilter): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchProducts(to_candid_ProductFilter_n42(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchProducts(to_candid_ProductFilter_n42(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async setCartQuantity(arg0: ProductId, arg1: bigint): Promise<CartError> {
        if (this.processError) {
            try {
                const result = await this.actor.setCartQuantity(arg0, arg1);
                return from_candid_CartError_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setCartQuantity(arg0, arg1);
            return from_candid_CartError_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async toggleWishlist(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleWishlist(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleWishlist(arg0);
            return result;
        }
    }
    async updateAddress(arg0: AddressId, arg1: Address): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAddress(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAddress(arg0, arg1);
            return result;
        }
    }
}
function from_candid_CartError_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CartError): CartError {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_CartView_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CartView): CartView {
    return from_candid_record_n32(_uploadFile, _downloadFile, value);
}
function from_candid_Cell_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Cell): Cell {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
function from_candid_CustomerSummary_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CustomerSummary): CustomerSummary {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Error_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Error): Error_ {
    return from_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return "outForDelivery" in value ? OrderStatus.outForDelivery : "placed" in value ? OrderStatus.placed : "packing" in value ? OrderStatus.packing : "delivered" in value ? OrderStatus.delivered : "confirmed" in value ? OrderStatus.confirmed : value;
}
function from_candid_Order_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return "cod" in value ? PaymentMethod.cod : "online" in value ? PaymentMethod.online : value;
}
function from_candid_Result__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result__1): Result__1 {
    return from_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_record_n20(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_Value_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Value): Value {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n28(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Category]): Category | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Product]): Product | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _OrderId;
    status: _OrderStatus;
    couponCode: [] | [string];
    deliveryCharge: _Paise;
    total: _Paise;
    paymentMethod: _PaymentMethod;
    lines: Array<_OrderLine>;
    couponDiscount: _Paise;
    updatedAt: _Timestamp;
    address: _Address;
    placedAt: _Timestamp;
    subtotal: _Paise;
    discountTotal: _Paise;
}): {
    id: OrderId;
    status: OrderStatus;
    couponCode?: string;
    deliveryCharge: Paise;
    total: Paise;
    paymentMethod: PaymentMethod;
    lines: Array<OrderLine>;
    couponDiscount: Paise;
    updatedAt: Timestamp;
    address: Address;
    placedAt: Timestamp;
    subtotal: Paise;
    discountTotal: Paise;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n15(_uploadFile, _downloadFile, value.status),
        couponCode: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.couponCode)),
        deliveryCharge: value.deliveryCharge,
        total: value.total,
        paymentMethod: from_candid_PaymentMethod_n16(_uploadFile, _downloadFile, value.paymentMethod),
        lines: value.lines,
        couponDiscount: value.couponDiscount,
        updatedAt: value.updatedAt,
        address: value.address,
        placedAt: value.placedAt,
        subtotal: value.subtotal,
        discountTotal: value.discountTotal
    };
}
function from_candid_record_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hasMore: boolean;
    rows: Array<Array<_Cell>>;
}): {
    hasMore: boolean;
    rows: Array<Array<Cell>>;
} {
    return {
        hasMore: value.hasMore,
        rows: from_candid_vec_n21(_uploadFile, _downloadFile, value.rows)
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    value: _Value;
    name: string;
}): {
    value: Value;
    name: string;
} {
    return {
        value: from_candid_Value_n25(_uploadFile, _downloadFile, value.value),
        name: value.name
    };
}
function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email: [] | [string];
}): {
    name: string;
    email?: string;
} {
    return {
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.email))
    };
}
function from_candid_record_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    couponCode: [] | [string];
    deliveryCharge: _Paise;
    total: _Paise;
    itemCount: bigint;
    couponDiscount: _Paise;
    items: Array<_CartItemView>;
    freeDeliveryThreshold: _Paise;
    subtotal: _Paise;
    discountTotal: _Paise;
}): {
    couponCode?: string;
    deliveryCharge: Paise;
    total: Paise;
    itemCount: bigint;
    couponDiscount: Paise;
    items: Array<CartItemView>;
    freeDeliveryThreshold: Paise;
    subtotal: Paise;
    discountTotal: Paise;
} {
    return {
        couponCode: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.couponCode)),
        deliveryCharge: value.deliveryCharge,
        total: value.total,
        itemCount: value.itemCount,
        couponDiscount: value.couponDiscount,
        items: value.items,
        freeDeliveryThreshold: value.freeDeliveryThreshold,
        subtotal: value.subtotal,
        discountTotal: value.discountTotal
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    principal: Principal;
    name: string;
    email: [] | [string];
    orderCount: bigint;
    totalSpent: _Paise;
}): {
    principal: Principal;
    name: string;
    email?: string;
    orderCount: bigint;
    totalSpent: Paise;
} {
    return {
        principal: value.principal,
        name: value.name,
        email: record_opt_to_undefined(from_candid_opt_n10(_uploadFile, _downloadFile, value.email)),
        orderCount: value.orderCount,
        totalSpent: value.totalSpent
    };
}
function from_candid_tuple_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [Principal, _Order]): [Principal, Order] {
    return [
        value[0],
        from_candid_Order_n13(_uploadFile, _downloadFile, value[1])
    ];
}
function from_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: _Error;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: Error_;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: from_candid_Error_n3(_uploadFile, _downloadFile, value.err)
    } : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    int: bigint;
} | {
    nat: bigint;
} | {
    float: number;
} | {
    bool: boolean;
} | {
    null: null;
} | {
    text: string;
}): {
    __kind__: "int";
    int: bigint;
} | {
    __kind__: "nat";
    nat: bigint;
} | {
    __kind__: "float";
    float: number;
} | {
    __kind__: "bool";
    bool: boolean;
} | {
    __kind__: "null";
    null: null;
} | {
    __kind__: "text";
    text: string;
} {
    return "int" in value ? {
        __kind__: "int",
        int: value.int
    } : "nat" in value ? {
        __kind__: "nat",
        nat: value.nat
    } : "float" in value ? {
        __kind__: "float",
        float: value.float
    } : "bool" in value ? {
        __kind__: "bool",
        bool: value.bool
    } : "null" in value ? {
        __kind__: "null",
        null: value.null
    } : "text" in value ? {
        __kind__: "text",
        text: value.text
    } : value;
}
function from_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    FrontendOriginsNotConfigured: null;
} | {
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    Stale: {
        ageNs: bigint;
    };
} | {
    MalformedCandid: null;
} | {
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    NoAttributes: null;
} | {
    UnknownNonce: null;
} | {
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    MissingField: string;
} | {
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
}): {
    __kind__: "FrontendOriginsNotConfigured";
    FrontendOriginsNotConfigured: null;
} | {
    __kind__: "MixedSsoSources";
    MixedSsoSources: {
        otherKeys: Array<string>;
        ssoKeys: Array<string>;
    };
} | {
    __kind__: "Stale";
    Stale: {
        ageNs: bigint;
    };
} | {
    __kind__: "MalformedCandid";
    MalformedCandid: null;
} | {
    __kind__: "AmbiguousAttribute";
    AmbiguousAttribute: {
        field: string;
        sources: Array<string>;
    };
} | {
    __kind__: "NoAttributes";
    NoAttributes: null;
} | {
    __kind__: "UnknownNonce";
    UnknownNonce: null;
} | {
    __kind__: "UntrustedSsoSource";
    UntrustedSsoSource: {
        domain: string;
    };
} | {
    __kind__: "MissingField";
    MissingField: string;
} | {
    __kind__: "FrontendOriginMismatch";
    FrontendOriginMismatch: {
        got: string;
        expected: Array<string>;
    };
} {
    return "FrontendOriginsNotConfigured" in value ? {
        __kind__: "FrontendOriginsNotConfigured",
        FrontendOriginsNotConfigured: value.FrontendOriginsNotConfigured
    } : "MixedSsoSources" in value ? {
        __kind__: "MixedSsoSources",
        MixedSsoSources: value.MixedSsoSources
    } : "Stale" in value ? {
        __kind__: "Stale",
        Stale: value.Stale
    } : "MalformedCandid" in value ? {
        __kind__: "MalformedCandid",
        MalformedCandid: value.MalformedCandid
    } : "AmbiguousAttribute" in value ? {
        __kind__: "AmbiguousAttribute",
        AmbiguousAttribute: value.AmbiguousAttribute
    } : "NoAttributes" in value ? {
        __kind__: "NoAttributes",
        NoAttributes: value.NoAttributes
    } : "UnknownNonce" in value ? {
        __kind__: "UnknownNonce",
        UnknownNonce: value.UnknownNonce
    } : "UntrustedSsoSource" in value ? {
        __kind__: "UntrustedSsoSource",
        UntrustedSsoSource: value.UntrustedSsoSource
    } : "MissingField" in value ? {
        __kind__: "MissingField",
        MissingField: value.MissingField
    } : "FrontendOriginMismatch" in value ? {
        __kind__: "FrontendOriginMismatch",
        FrontendOriginMismatch: value.FrontendOriginMismatch
    } : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    productNotFound: _ProductId;
} | {
    couponInactive: string;
} | {
    invalidAddress: string;
} | {
    couponNotFound: string;
} | {
    outOfStock: _ProductId;
} | {
    invalidPincode: string;
} | {
    couponMinOrderNotMet: {
        actual: _Paise;
        required: _Paise;
    };
} | {
    invalidMobile: string;
} | {
    invalidQuantity: null;
} | {
    emptyCart: null;
}): {
    __kind__: "productNotFound";
    productNotFound: ProductId;
} | {
    __kind__: "couponInactive";
    couponInactive: string;
} | {
    __kind__: "invalidAddress";
    invalidAddress: string;
} | {
    __kind__: "couponNotFound";
    couponNotFound: string;
} | {
    __kind__: "outOfStock";
    outOfStock: ProductId;
} | {
    __kind__: "invalidPincode";
    invalidPincode: string;
} | {
    __kind__: "couponMinOrderNotMet";
    couponMinOrderNotMet: {
        actual: Paise;
        required: Paise;
    };
} | {
    __kind__: "invalidMobile";
    invalidMobile: string;
} | {
    __kind__: "invalidQuantity";
    invalidQuantity: null;
} | {
    __kind__: "emptyCart";
    emptyCart: null;
} {
    return "productNotFound" in value ? {
        __kind__: "productNotFound",
        productNotFound: value.productNotFound
    } : "couponInactive" in value ? {
        __kind__: "couponInactive",
        couponInactive: value.couponInactive
    } : "invalidAddress" in value ? {
        __kind__: "invalidAddress",
        invalidAddress: value.invalidAddress
    } : "couponNotFound" in value ? {
        __kind__: "couponNotFound",
        couponNotFound: value.couponNotFound
    } : "outOfStock" in value ? {
        __kind__: "outOfStock",
        outOfStock: value.outOfStock
    } : "invalidPincode" in value ? {
        __kind__: "invalidPincode",
        invalidPincode: value.invalidPincode
    } : "couponMinOrderNotMet" in value ? {
        __kind__: "couponMinOrderNotMet",
        couponMinOrderNotMet: value.couponMinOrderNotMet
    } : "invalidMobile" in value ? {
        __kind__: "invalidMobile",
        invalidMobile: value.invalidMobile
    } : "invalidQuantity" in value ? {
        __kind__: "invalidQuantity",
        invalidQuantity: value.invalidQuantity
    } : "emptyCart" in value ? {
        __kind__: "emptyCart",
        emptyCart: value.emptyCart
    } : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<[Principal, _Order]>): Array<[Principal, Order]> {
    return value.map((x)=>from_candid_tuple_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<Array<_Cell>>): Array<Array<Cell>> {
    return value.map((x)=>from_candid_vec_n22(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Cell>): Array<Cell> {
    return value.map((x)=>from_candid_Cell_n23(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CustomerSummary>): Array<CustomerSummary> {
    return value.map((x)=>from_candid_CustomerSummary_n8(_uploadFile, _downloadFile, x));
}
function to_candid_CheckoutInput_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CheckoutInput): _CheckoutInput {
    return to_candid_record_n38(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return value == OrderStatus.outForDelivery ? {
        outForDelivery: null
    } : value == OrderStatus.placed ? {
        placed: null
    } : value == OrderStatus.packing ? {
        packing: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_PaymentMethod_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return value == PaymentMethod.cod ? {
        cod: null
    } : value == PaymentMethod.online ? {
        online: null
    } : value;
}
function to_candid_ProductFilter_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductFilter): _ProductFilter {
    return to_candid_record_n43(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n41(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    couponCode?: string;
    paymentMethod: PaymentMethod;
    address: Address;
}): {
    couponCode: [] | [string];
    paymentMethod: _PaymentMethod;
    address: _Address;
} {
    return {
        couponCode: value.couponCode ? candid_some(value.couponCode) : candid_none(),
        paymentMethod: to_candid_PaymentMethod_n39(_uploadFile, _downloadFile, value.paymentMethod),
        address: value.address
    };
}
function to_candid_record_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: string;
    email?: string;
}): {
    name: string;
    email: [] | [string];
} {
    return {
        name: value.name,
        email: value.email ? candid_some(value.email) : candid_none()
    };
}
function to_candid_record_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    categoryId?: CategoryId;
    inStockOnly: boolean;
    maxPrice?: Paise;
    searchTerm?: string;
    minPrice?: Paise;
}): {
    categoryId: [] | [_CategoryId];
    inStockOnly: boolean;
    maxPrice: [] | [_Paise];
    searchTerm: [] | [string];
    minPrice: [] | [_Paise];
} {
    return {
        categoryId: value.categoryId ? candid_some(value.categoryId) : candid_none(),
        inStockOnly: value.inStockOnly,
        maxPrice: value.maxPrice ? candid_some(value.maxPrice) : candid_none(),
        searchTerm: value.searchTerm ? candid_some(value.searchTerm) : candid_none(),
        minPrice: value.minPrice ? candid_some(value.minPrice) : candid_none()
    };
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
